version: 0.2

phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - npm run astro check
  build:
    commands:
      - npm run build
artifacts:
  files:
    - 'dist/*'
  discard-paths: yes